### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by MariusTheisen** [pytools4dart/pytools4dart#1]
I have problems with the installation during the step:

`python -c “import pytools4dart as ptd; ptd.configure(r‘~/DART’)”`

The following error appears:

![Screenshot 2024-09-19 163700](https://github.com/user-attachments/assets/96ba586f-9831-4b4f-9a8c-5e5714e4eb6c)

Is there an easy fix for the problem? I have already tried to change `isdir` to `is_dir` in settings.py.

**Comment by floriandeboissieu** [comment]
This [issue](https://gitlab.com/pytools4dart/pytools4dart/-/issues/42) was fixed in dev branch. I will make a new release as soon as possible. Until then, you can install dev version with:
```shell
pip install git+https://gitlab.com/pytools4dart/pytools4dart@dev
```

**Comment by MariusTheisen** [comment]
Thank you for the quick and helpful reply. This solved the problem for me.

**Comment by floriandeboissieu** [comment]
Thanks for your feedback.

I published the new version including `path>=17` in the dependencies.
